environment:
  matrix:
    - build_name: mingw73_32_qt5_12_5
      QTPATH: C:\Qt\5.12.5\mingw73_32
      MINGW32: C:\Qt\Tools\mingw730_32
#    - build_name: msvc2017_64
#      QTPATH: C:\Qt\5.11.2\msvc2017_64
#      MINGW32: C:\Qt\Tools\mingw530_32

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - set PATH=%PATH%;%QTPATH%\bin;%MINGW32%\bin

build_script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_MAKE_PROGRAM=mingw32-make ..\
  - mingw32-make
  - mkdir cmake_release_folder
  - cd cmake_release_folder
  - copy ..\ppic.exe .\
  - windeployqt --no-quick-import --no-translations --no-opengl-sw --no-angle --no-system-d3d-compiler --release .\ppic.exe

artifacts:
  - path: build\cmake_release_folder
